-- auto Generated on 2019-11-11
-- DROP TABLE IF EXISTS t_image;
CREATE TABLE t_image(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'title',
	`desc` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'desc',
	src VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'src',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_image';
